#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSaver
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FoodDB")]
	public partial class LinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFood(Food instance);
    partial void UpdateFood(Food instance);
    partial void DeleteFood(Food instance);
    partial void InsertValueTable(ValueTable instance);
    partial void UpdateValueTable(ValueTable instance);
    partial void DeleteValueTable(ValueTable instance);
    partial void InsertFoodQuality(FoodQuality instance);
    partial void UpdateFoodQuality(FoodQuality instance);
    partial void DeleteFoodQuality(FoodQuality instance);
    partial void InsertFoodShopRelation(FoodShopRelation instance);
    partial void UpdateFoodShopRelation(FoodShopRelation instance);
    partial void DeleteFoodShopRelation(FoodShopRelation instance);
    partial void InsertFoodShopRelationBuy(FoodShopRelationBuy instance);
    partial void UpdateFoodShopRelationBuy(FoodShopRelationBuy instance);
    partial void DeleteFoodShopRelationBuy(FoodShopRelationBuy instance);
    partial void InsertHistory(History instance);
    partial void UpdateHistory(History instance);
    partial void DeleteHistory(History instance);
    partial void InsertImagesTable(ImagesTable instance);
    partial void UpdateImagesTable(ImagesTable instance);
    partial void DeleteImagesTable(ImagesTable instance);
    partial void InsertLoginTable(LoginTable instance);
    partial void UpdateLoginTable(LoginTable instance);
    partial void DeleteLoginTable(LoginTable instance);
    partial void InsertShopLocation(ShopLocation instance);
    partial void UpdateShopLocation(ShopLocation instance);
    partial void DeleteShopLocation(ShopLocation instance);
    #endregion
		
		public LinqToSqlDataContext() : 
				base(global::FoodSaver.Properties.Settings.Default.FoodDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Food> Foods
		{
			get
			{
				return this.GetTable<Food>();
			}
		}
		
		public System.Data.Linq.Table<ValueTable> ValueTables
		{
			get
			{
				return this.GetTable<ValueTable>();
			}
		}
		
		public System.Data.Linq.Table<FoodQuality> FoodQualities
		{
			get
			{
				return this.GetTable<FoodQuality>();
			}
		}
		
		public System.Data.Linq.Table<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this.GetTable<FoodShopRelation>();
			}
		}
		
		public System.Data.Linq.Table<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this.GetTable<FoodShopRelationBuy>();
			}
		}
		
		public System.Data.Linq.Table<History> Histories
		{
			get
			{
				return this.GetTable<History>();
			}
		}
		
		public System.Data.Linq.Table<ImagesTable> ImagesTables
		{
			get
			{
				return this.GetTable<ImagesTable>();
			}
		}
		
		public System.Data.Linq.Table<LoginTable> LoginTables
		{
			get
			{
				return this.GetTable<LoginTable>();
			}
		}
		
		public System.Data.Linq.Table<ShopLocation> ShopLocations
		{
			get
			{
				return this.GetTable<ShopLocation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Food")]
	public partial class Food : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private EntitySet<FoodShopRelation> _FoodShopRelations;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Food()
		{
			this._FoodShopRelations = new EntitySet<FoodShopRelation>(new Action<FoodShopRelation>(this.attach_FoodShopRelations), new Action<FoodShopRelation>(this.detach_FoodShopRelations));
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_FoodShopRelation", Storage="_FoodShopRelations", ThisKey="Id", OtherKey="FoodID")]
		public EntitySet<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this._FoodShopRelations;
			}
			set
			{
				this._FoodShopRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="FoodID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_History", Storage="_Histories", ThisKey="Id", OtherKey="FoodID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.Food = this;
		}
		
		private void detach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.Food = null;
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.Food = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.Food = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.Food = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.Food = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ValueTable")]
	public partial class ValueTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _FoodValue;
		
		private EntitySet<FoodShopRelation> _FoodShopRelations;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFoodValueChanging(int value);
    partial void OnFoodValueChanged();
    #endregion
		
		public ValueTable()
		{
			this._FoodShopRelations = new EntitySet<FoodShopRelation>(new Action<FoodShopRelation>(this.attach_FoodShopRelations), new Action<FoodShopRelation>(this.detach_FoodShopRelations));
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodValue", DbType="Int NOT NULL")]
		public int FoodValue
		{
			get
			{
				return this._FoodValue;
			}
			set
			{
				if ((this._FoodValue != value))
				{
					this.OnFoodValueChanging(value);
					this.SendPropertyChanging();
					this._FoodValue = value;
					this.SendPropertyChanged("FoodValue");
					this.OnFoodValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_FoodShopRelation", Storage="_FoodShopRelations", ThisKey="Id", OtherKey="ValueTableID")]
		public EntitySet<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this._FoodShopRelations;
			}
			set
			{
				this._FoodShopRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="ValueTableID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_History", Storage="_Histories", ThisKey="Id", OtherKey="ValueTableID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = this;
		}
		
		private void detach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = null;
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ValueTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodQuality")]
	public partial class FoodQuality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Quality;
		
		private EntitySet<FoodShopRelation> _FoodShopRelations;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnQualityChanging(int value);
    partial void OnQualityChanged();
    #endregion
		
		public FoodQuality()
		{
			this._FoodShopRelations = new EntitySet<FoodShopRelation>(new Action<FoodShopRelation>(this.attach_FoodShopRelations), new Action<FoodShopRelation>(this.detach_FoodShopRelations));
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality", DbType="Int NOT NULL")]
		public int Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				if ((this._Quality != value))
				{
					this.OnQualityChanging(value);
					this.SendPropertyChanging();
					this._Quality = value;
					this.SendPropertyChanged("Quality");
					this.OnQualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_FoodShopRelation", Storage="_FoodShopRelations", ThisKey="Id", OtherKey="FoodQualityID")]
		public EntitySet<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this._FoodShopRelations;
			}
			set
			{
				this._FoodShopRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="FoodQualityID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_History", Storage="_Histories", ThisKey="Id", OtherKey="FoodQualityID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = this;
		}
		
		private void detach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = null;
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.FoodQuality = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodShopRelation")]
	public partial class FoodShopRelation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _FoodID;
		
		private int _ShopLocationID;
		
		private int _ImagesTableID;
		
		private int _ValueTableID;
		
		private int _FoodQualityID;
		
		private EntityRef<Food> _Food;
		
		private EntityRef<FoodQuality> _FoodQuality;
		
		private EntityRef<ValueTable> _ValueTable;
		
		private EntityRef<ImagesTable> _ImagesTable;
		
		private EntityRef<ShopLocation> _ShopLocation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFoodIDChanging(int value);
    partial void OnFoodIDChanged();
    partial void OnShopLocationIDChanging(int value);
    partial void OnShopLocationIDChanged();
    partial void OnImagesTableIDChanging(int value);
    partial void OnImagesTableIDChanged();
    partial void OnValueTableIDChanging(int value);
    partial void OnValueTableIDChanged();
    partial void OnFoodQualityIDChanging(int value);
    partial void OnFoodQualityIDChanged();
    #endregion
		
		public FoodShopRelation()
		{
			this._Food = default(EntityRef<Food>);
			this._FoodQuality = default(EntityRef<FoodQuality>);
			this._ValueTable = default(EntityRef<ValueTable>);
			this._ImagesTable = default(EntityRef<ImagesTable>);
			this._ShopLocation = default(EntityRef<ShopLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodID", DbType="Int NOT NULL")]
		public int FoodID
		{
			get
			{
				return this._FoodID;
			}
			set
			{
				if ((this._FoodID != value))
				{
					if (this._Food.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodIDChanging(value);
					this.SendPropertyChanging();
					this._FoodID = value;
					this.SendPropertyChanged("FoodID");
					this.OnFoodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopLocationID", DbType="Int NOT NULL")]
		public int ShopLocationID
		{
			get
			{
				return this._ShopLocationID;
			}
			set
			{
				if ((this._ShopLocationID != value))
				{
					if (this._ShopLocation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShopLocationIDChanging(value);
					this.SendPropertyChanging();
					this._ShopLocationID = value;
					this.SendPropertyChanged("ShopLocationID");
					this.OnShopLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagesTableID", DbType="Int NOT NULL")]
		public int ImagesTableID
		{
			get
			{
				return this._ImagesTableID;
			}
			set
			{
				if ((this._ImagesTableID != value))
				{
					if (this._ImagesTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnImagesTableIDChanging(value);
					this.SendPropertyChanging();
					this._ImagesTableID = value;
					this.SendPropertyChanged("ImagesTableID");
					this.OnImagesTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueTableID", DbType="Int NOT NULL")]
		public int ValueTableID
		{
			get
			{
				return this._ValueTableID;
			}
			set
			{
				if ((this._ValueTableID != value))
				{
					if (this._ValueTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnValueTableIDChanging(value);
					this.SendPropertyChanging();
					this._ValueTableID = value;
					this.SendPropertyChanged("ValueTableID");
					this.OnValueTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodQualityID", DbType="Int NOT NULL")]
		public int FoodQualityID
		{
			get
			{
				return this._FoodQualityID;
			}
			set
			{
				if ((this._FoodQualityID != value))
				{
					if (this._FoodQuality.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodQualityIDChanging(value);
					this.SendPropertyChanging();
					this._FoodQualityID = value;
					this.SendPropertyChanged("FoodQualityID");
					this.OnFoodQualityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_FoodShopRelation", Storage="_Food", ThisKey="FoodID", OtherKey="Id", IsForeignKey=true)]
		public Food Food
		{
			get
			{
				return this._Food.Entity;
			}
			set
			{
				Food previousValue = this._Food.Entity;
				if (((previousValue != value) 
							|| (this._Food.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Food.Entity = null;
						previousValue.FoodShopRelations.Remove(this);
					}
					this._Food.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelations.Add(this);
						this._FoodID = value.Id;
					}
					else
					{
						this._FoodID = default(int);
					}
					this.SendPropertyChanged("Food");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_FoodShopRelation", Storage="_FoodQuality", ThisKey="FoodQualityID", OtherKey="Id", IsForeignKey=true)]
		public FoodQuality FoodQuality
		{
			get
			{
				return this._FoodQuality.Entity;
			}
			set
			{
				FoodQuality previousValue = this._FoodQuality.Entity;
				if (((previousValue != value) 
							|| (this._FoodQuality.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodQuality.Entity = null;
						previousValue.FoodShopRelations.Remove(this);
					}
					this._FoodQuality.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelations.Add(this);
						this._FoodQualityID = value.Id;
					}
					else
					{
						this._FoodQualityID = default(int);
					}
					this.SendPropertyChanged("FoodQuality");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_FoodShopRelation", Storage="_ValueTable", ThisKey="ValueTableID", OtherKey="Id", IsForeignKey=true)]
		public ValueTable ValueTable
		{
			get
			{
				return this._ValueTable.Entity;
			}
			set
			{
				ValueTable previousValue = this._ValueTable.Entity;
				if (((previousValue != value) 
							|| (this._ValueTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ValueTable.Entity = null;
						previousValue.FoodShopRelations.Remove(this);
					}
					this._ValueTable.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelations.Add(this);
						this._ValueTableID = value.Id;
					}
					else
					{
						this._ValueTableID = default(int);
					}
					this.SendPropertyChanged("ValueTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_FoodShopRelation", Storage="_ImagesTable", ThisKey="ImagesTableID", OtherKey="Id", IsForeignKey=true)]
		public ImagesTable ImagesTable
		{
			get
			{
				return this._ImagesTable.Entity;
			}
			set
			{
				ImagesTable previousValue = this._ImagesTable.Entity;
				if (((previousValue != value) 
							|| (this._ImagesTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ImagesTable.Entity = null;
						previousValue.FoodShopRelations.Remove(this);
					}
					this._ImagesTable.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelations.Add(this);
						this._ImagesTableID = value.Id;
					}
					else
					{
						this._ImagesTableID = default(int);
					}
					this.SendPropertyChanged("ImagesTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_FoodShopRelation", Storage="_ShopLocation", ThisKey="ShopLocationID", OtherKey="Id", IsForeignKey=true)]
		public ShopLocation ShopLocation
		{
			get
			{
				return this._ShopLocation.Entity;
			}
			set
			{
				ShopLocation previousValue = this._ShopLocation.Entity;
				if (((previousValue != value) 
							|| (this._ShopLocation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShopLocation.Entity = null;
						previousValue.FoodShopRelations.Remove(this);
					}
					this._ShopLocation.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelations.Add(this);
						this._ShopLocationID = value.Id;
					}
					else
					{
						this._ShopLocationID = default(int);
					}
					this.SendPropertyChanged("ShopLocation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodShopRelationBuy")]
	public partial class FoodShopRelationBuy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _FoodID;
		
		private int _ShopLocationID;
		
		private int _ImagesTableID;
		
		private int _ValueTableID;
		
		private int _LoginTableID;
		
		private int _FoodQualityID;
		
		private EntityRef<Food> _Food;
		
		private EntityRef<FoodQuality> _FoodQuality;
		
		private EntityRef<ValueTable> _ValueTable;
		
		private EntityRef<ImagesTable> _ImagesTable;
		
		private EntityRef<LoginTable> _LoginTable;
		
		private EntityRef<ShopLocation> _ShopLocation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFoodIDChanging(int value);
    partial void OnFoodIDChanged();
    partial void OnShopLocationIDChanging(int value);
    partial void OnShopLocationIDChanged();
    partial void OnImagesTableIDChanging(int value);
    partial void OnImagesTableIDChanged();
    partial void OnValueTableIDChanging(int value);
    partial void OnValueTableIDChanged();
    partial void OnLoginTableIDChanging(int value);
    partial void OnLoginTableIDChanged();
    partial void OnFoodQualityIDChanging(int value);
    partial void OnFoodQualityIDChanged();
    #endregion
		
		public FoodShopRelationBuy()
		{
			this._Food = default(EntityRef<Food>);
			this._FoodQuality = default(EntityRef<FoodQuality>);
			this._ValueTable = default(EntityRef<ValueTable>);
			this._ImagesTable = default(EntityRef<ImagesTable>);
			this._LoginTable = default(EntityRef<LoginTable>);
			this._ShopLocation = default(EntityRef<ShopLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodID", DbType="Int NOT NULL")]
		public int FoodID
		{
			get
			{
				return this._FoodID;
			}
			set
			{
				if ((this._FoodID != value))
				{
					if (this._Food.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodIDChanging(value);
					this.SendPropertyChanging();
					this._FoodID = value;
					this.SendPropertyChanged("FoodID");
					this.OnFoodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopLocationID", DbType="Int NOT NULL")]
		public int ShopLocationID
		{
			get
			{
				return this._ShopLocationID;
			}
			set
			{
				if ((this._ShopLocationID != value))
				{
					if (this._ShopLocation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShopLocationIDChanging(value);
					this.SendPropertyChanging();
					this._ShopLocationID = value;
					this.SendPropertyChanged("ShopLocationID");
					this.OnShopLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagesTableID", DbType="Int NOT NULL")]
		public int ImagesTableID
		{
			get
			{
				return this._ImagesTableID;
			}
			set
			{
				if ((this._ImagesTableID != value))
				{
					if (this._ImagesTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnImagesTableIDChanging(value);
					this.SendPropertyChanging();
					this._ImagesTableID = value;
					this.SendPropertyChanged("ImagesTableID");
					this.OnImagesTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueTableID", DbType="Int NOT NULL")]
		public int ValueTableID
		{
			get
			{
				return this._ValueTableID;
			}
			set
			{
				if ((this._ValueTableID != value))
				{
					if (this._ValueTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnValueTableIDChanging(value);
					this.SendPropertyChanging();
					this._ValueTableID = value;
					this.SendPropertyChanged("ValueTableID");
					this.OnValueTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTableID", DbType="Int NOT NULL")]
		public int LoginTableID
		{
			get
			{
				return this._LoginTableID;
			}
			set
			{
				if ((this._LoginTableID != value))
				{
					if (this._LoginTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoginTableIDChanging(value);
					this.SendPropertyChanging();
					this._LoginTableID = value;
					this.SendPropertyChanged("LoginTableID");
					this.OnLoginTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodQualityID", DbType="Int NOT NULL")]
		public int FoodQualityID
		{
			get
			{
				return this._FoodQualityID;
			}
			set
			{
				if ((this._FoodQualityID != value))
				{
					if (this._FoodQuality.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodQualityIDChanging(value);
					this.SendPropertyChanging();
					this._FoodQualityID = value;
					this.SendPropertyChanged("FoodQualityID");
					this.OnFoodQualityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_FoodShopRelationBuy", Storage="_Food", ThisKey="FoodID", OtherKey="Id", IsForeignKey=true)]
		public Food Food
		{
			get
			{
				return this._Food.Entity;
			}
			set
			{
				Food previousValue = this._Food.Entity;
				if (((previousValue != value) 
							|| (this._Food.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Food.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._Food.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._FoodID = value.Id;
					}
					else
					{
						this._FoodID = default(int);
					}
					this.SendPropertyChanged("Food");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_FoodShopRelationBuy", Storage="_FoodQuality", ThisKey="FoodQualityID", OtherKey="Id", IsForeignKey=true)]
		public FoodQuality FoodQuality
		{
			get
			{
				return this._FoodQuality.Entity;
			}
			set
			{
				FoodQuality previousValue = this._FoodQuality.Entity;
				if (((previousValue != value) 
							|| (this._FoodQuality.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodQuality.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._FoodQuality.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._FoodQualityID = value.Id;
					}
					else
					{
						this._FoodQualityID = default(int);
					}
					this.SendPropertyChanged("FoodQuality");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_FoodShopRelationBuy", Storage="_ValueTable", ThisKey="ValueTableID", OtherKey="Id", IsForeignKey=true)]
		public ValueTable ValueTable
		{
			get
			{
				return this._ValueTable.Entity;
			}
			set
			{
				ValueTable previousValue = this._ValueTable.Entity;
				if (((previousValue != value) 
							|| (this._ValueTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ValueTable.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._ValueTable.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._ValueTableID = value.Id;
					}
					else
					{
						this._ValueTableID = default(int);
					}
					this.SendPropertyChanged("ValueTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_FoodShopRelationBuy", Storage="_ImagesTable", ThisKey="ImagesTableID", OtherKey="Id", IsForeignKey=true)]
		public ImagesTable ImagesTable
		{
			get
			{
				return this._ImagesTable.Entity;
			}
			set
			{
				ImagesTable previousValue = this._ImagesTable.Entity;
				if (((previousValue != value) 
							|| (this._ImagesTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ImagesTable.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._ImagesTable.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._ImagesTableID = value.Id;
					}
					else
					{
						this._ImagesTableID = default(int);
					}
					this.SendPropertyChanged("ImagesTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoginTable_FoodShopRelationBuy", Storage="_LoginTable", ThisKey="LoginTableID", OtherKey="Id", IsForeignKey=true)]
		public LoginTable LoginTable
		{
			get
			{
				return this._LoginTable.Entity;
			}
			set
			{
				LoginTable previousValue = this._LoginTable.Entity;
				if (((previousValue != value) 
							|| (this._LoginTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoginTable.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._LoginTable.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._LoginTableID = value.Id;
					}
					else
					{
						this._LoginTableID = default(int);
					}
					this.SendPropertyChanged("LoginTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_FoodShopRelationBuy", Storage="_ShopLocation", ThisKey="ShopLocationID", OtherKey="Id", IsForeignKey=true)]
		public ShopLocation ShopLocation
		{
			get
			{
				return this._ShopLocation.Entity;
			}
			set
			{
				ShopLocation previousValue = this._ShopLocation.Entity;
				if (((previousValue != value) 
							|| (this._ShopLocation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShopLocation.Entity = null;
						previousValue.FoodShopRelationBuys.Remove(this);
					}
					this._ShopLocation.Entity = value;
					if ((value != null))
					{
						value.FoodShopRelationBuys.Add(this);
						this._ShopLocationID = value.Id;
					}
					else
					{
						this._ShopLocationID = default(int);
					}
					this.SendPropertyChanged("ShopLocation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.History")]
	public partial class History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _FoodID;
		
		private int _ShopLocationID;
		
		private int _ImagesTableID;
		
		private int _ValueTableID;
		
		private int _LoginTableID;
		
		private string _Refund;
		
		private System.DateTime _Time;
		
		private int _FoodQualityID;
		
		private EntityRef<Food> _Food;
		
		private EntityRef<FoodQuality> _FoodQuality;
		
		private EntityRef<ValueTable> _ValueTable;
		
		private EntityRef<ImagesTable> _ImagesTable;
		
		private EntityRef<LoginTable> _LoginTable;
		
		private EntityRef<ShopLocation> _ShopLocation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFoodIDChanging(int value);
    partial void OnFoodIDChanged();
    partial void OnShopLocationIDChanging(int value);
    partial void OnShopLocationIDChanged();
    partial void OnImagesTableIDChanging(int value);
    partial void OnImagesTableIDChanged();
    partial void OnValueTableIDChanging(int value);
    partial void OnValueTableIDChanged();
    partial void OnLoginTableIDChanging(int value);
    partial void OnLoginTableIDChanged();
    partial void OnRefundChanging(string value);
    partial void OnRefundChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnFoodQualityIDChanging(int value);
    partial void OnFoodQualityIDChanged();
    #endregion
		
		public History()
		{
			this._Food = default(EntityRef<Food>);
			this._FoodQuality = default(EntityRef<FoodQuality>);
			this._ValueTable = default(EntityRef<ValueTable>);
			this._ImagesTable = default(EntityRef<ImagesTable>);
			this._LoginTable = default(EntityRef<LoginTable>);
			this._ShopLocation = default(EntityRef<ShopLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodID", DbType="Int NOT NULL")]
		public int FoodID
		{
			get
			{
				return this._FoodID;
			}
			set
			{
				if ((this._FoodID != value))
				{
					if (this._Food.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodIDChanging(value);
					this.SendPropertyChanging();
					this._FoodID = value;
					this.SendPropertyChanged("FoodID");
					this.OnFoodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopLocationID", DbType="Int NOT NULL")]
		public int ShopLocationID
		{
			get
			{
				return this._ShopLocationID;
			}
			set
			{
				if ((this._ShopLocationID != value))
				{
					if (this._ShopLocation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShopLocationIDChanging(value);
					this.SendPropertyChanging();
					this._ShopLocationID = value;
					this.SendPropertyChanged("ShopLocationID");
					this.OnShopLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagesTableID", DbType="Int NOT NULL")]
		public int ImagesTableID
		{
			get
			{
				return this._ImagesTableID;
			}
			set
			{
				if ((this._ImagesTableID != value))
				{
					if (this._ImagesTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnImagesTableIDChanging(value);
					this.SendPropertyChanging();
					this._ImagesTableID = value;
					this.SendPropertyChanged("ImagesTableID");
					this.OnImagesTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueTableID", DbType="Int NOT NULL")]
		public int ValueTableID
		{
			get
			{
				return this._ValueTableID;
			}
			set
			{
				if ((this._ValueTableID != value))
				{
					if (this._ValueTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnValueTableIDChanging(value);
					this.SendPropertyChanging();
					this._ValueTableID = value;
					this.SendPropertyChanged("ValueTableID");
					this.OnValueTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTableID", DbType="Int NOT NULL")]
		public int LoginTableID
		{
			get
			{
				return this._LoginTableID;
			}
			set
			{
				if ((this._LoginTableID != value))
				{
					if (this._LoginTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoginTableIDChanging(value);
					this.SendPropertyChanging();
					this._LoginTableID = value;
					this.SendPropertyChanged("LoginTableID");
					this.OnLoginTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refund", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Refund
		{
			get
			{
				return this._Refund;
			}
			set
			{
				if ((this._Refund != value))
				{
					this.OnRefundChanging(value);
					this.SendPropertyChanging();
					this._Refund = value;
					this.SendPropertyChanged("Refund");
					this.OnRefundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodQualityID", DbType="Int NOT NULL")]
		public int FoodQualityID
		{
			get
			{
				return this._FoodQualityID;
			}
			set
			{
				if ((this._FoodQualityID != value))
				{
					if (this._FoodQuality.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodQualityIDChanging(value);
					this.SendPropertyChanging();
					this._FoodQualityID = value;
					this.SendPropertyChanged("FoodQualityID");
					this.OnFoodQualityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_History", Storage="_Food", ThisKey="FoodID", OtherKey="Id", IsForeignKey=true)]
		public Food Food
		{
			get
			{
				return this._Food.Entity;
			}
			set
			{
				Food previousValue = this._Food.Entity;
				if (((previousValue != value) 
							|| (this._Food.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Food.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._Food.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._FoodID = value.Id;
					}
					else
					{
						this._FoodID = default(int);
					}
					this.SendPropertyChanged("Food");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodQuality_History", Storage="_FoodQuality", ThisKey="FoodQualityID", OtherKey="Id", IsForeignKey=true)]
		public FoodQuality FoodQuality
		{
			get
			{
				return this._FoodQuality.Entity;
			}
			set
			{
				FoodQuality previousValue = this._FoodQuality.Entity;
				if (((previousValue != value) 
							|| (this._FoodQuality.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodQuality.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._FoodQuality.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._FoodQualityID = value.Id;
					}
					else
					{
						this._FoodQualityID = default(int);
					}
					this.SendPropertyChanged("FoodQuality");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ValueTable_History", Storage="_ValueTable", ThisKey="ValueTableID", OtherKey="Id", IsForeignKey=true)]
		public ValueTable ValueTable
		{
			get
			{
				return this._ValueTable.Entity;
			}
			set
			{
				ValueTable previousValue = this._ValueTable.Entity;
				if (((previousValue != value) 
							|| (this._ValueTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ValueTable.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._ValueTable.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._ValueTableID = value.Id;
					}
					else
					{
						this._ValueTableID = default(int);
					}
					this.SendPropertyChanged("ValueTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_History", Storage="_ImagesTable", ThisKey="ImagesTableID", OtherKey="Id", IsForeignKey=true)]
		public ImagesTable ImagesTable
		{
			get
			{
				return this._ImagesTable.Entity;
			}
			set
			{
				ImagesTable previousValue = this._ImagesTable.Entity;
				if (((previousValue != value) 
							|| (this._ImagesTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ImagesTable.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._ImagesTable.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._ImagesTableID = value.Id;
					}
					else
					{
						this._ImagesTableID = default(int);
					}
					this.SendPropertyChanged("ImagesTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoginTable_History", Storage="_LoginTable", ThisKey="LoginTableID", OtherKey="Id", IsForeignKey=true)]
		public LoginTable LoginTable
		{
			get
			{
				return this._LoginTable.Entity;
			}
			set
			{
				LoginTable previousValue = this._LoginTable.Entity;
				if (((previousValue != value) 
							|| (this._LoginTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoginTable.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._LoginTable.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._LoginTableID = value.Id;
					}
					else
					{
						this._LoginTableID = default(int);
					}
					this.SendPropertyChanged("LoginTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_History", Storage="_ShopLocation", ThisKey="ShopLocationID", OtherKey="Id", IsForeignKey=true)]
		public ShopLocation ShopLocation
		{
			get
			{
				return this._ShopLocation.Entity;
			}
			set
			{
				ShopLocation previousValue = this._ShopLocation.Entity;
				if (((previousValue != value) 
							|| (this._ShopLocation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShopLocation.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._ShopLocation.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._ShopLocationID = value.Id;
					}
					else
					{
						this._ShopLocationID = default(int);
					}
					this.SendPropertyChanged("ShopLocation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ImagesTable")]
	public partial class ImagesTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ImagePath;
		
		private EntitySet<FoodShopRelation> _FoodShopRelations;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    #endregion
		
		public ImagesTable()
		{
			this._FoodShopRelations = new EntitySet<FoodShopRelation>(new Action<FoodShopRelation>(this.attach_FoodShopRelations), new Action<FoodShopRelation>(this.detach_FoodShopRelations));
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_FoodShopRelation", Storage="_FoodShopRelations", ThisKey="Id", OtherKey="ImagesTableID")]
		public EntitySet<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this._FoodShopRelations;
			}
			set
			{
				this._FoodShopRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="ImagesTableID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ImagesTable_History", Storage="_Histories", ThisKey="Id", OtherKey="ImagesTableID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = this;
		}
		
		private void detach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = null;
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ImagesTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoginTable")]
	public partial class LoginTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _Password;
		
		private int _UserCoin;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserCoinChanging(int value);
    partial void OnUserCoinChanged();
    #endregion
		
		public LoginTable()
		{
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCoin", DbType="Int NOT NULL")]
		public int UserCoin
		{
			get
			{
				return this._UserCoin;
			}
			set
			{
				if ((this._UserCoin != value))
				{
					this.OnUserCoinChanging(value);
					this.SendPropertyChanging();
					this._UserCoin = value;
					this.SendPropertyChanged("UserCoin");
					this.OnUserCoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoginTable_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="LoginTableID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoginTable_History", Storage="_Histories", ThisKey="Id", OtherKey="LoginTableID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.LoginTable = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.LoginTable = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.LoginTable = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.LoginTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShopLocation")]
	public partial class ShopLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Location;
		
		private EntitySet<FoodShopRelation> _FoodShopRelations;
		
		private EntitySet<FoodShopRelationBuy> _FoodShopRelationBuys;
		
		private EntitySet<History> _Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    #endregion
		
		public ShopLocation()
		{
			this._FoodShopRelations = new EntitySet<FoodShopRelation>(new Action<FoodShopRelation>(this.attach_FoodShopRelations), new Action<FoodShopRelation>(this.detach_FoodShopRelations));
			this._FoodShopRelationBuys = new EntitySet<FoodShopRelationBuy>(new Action<FoodShopRelationBuy>(this.attach_FoodShopRelationBuys), new Action<FoodShopRelationBuy>(this.detach_FoodShopRelationBuys));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_FoodShopRelation", Storage="_FoodShopRelations", ThisKey="Id", OtherKey="ShopLocationID")]
		public EntitySet<FoodShopRelation> FoodShopRelations
		{
			get
			{
				return this._FoodShopRelations;
			}
			set
			{
				this._FoodShopRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_FoodShopRelationBuy", Storage="_FoodShopRelationBuys", ThisKey="Id", OtherKey="ShopLocationID")]
		public EntitySet<FoodShopRelationBuy> FoodShopRelationBuys
		{
			get
			{
				return this._FoodShopRelationBuys;
			}
			set
			{
				this._FoodShopRelationBuys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShopLocation_History", Storage="_Histories", ThisKey="Id", OtherKey="ShopLocationID")]
		public EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = this;
		}
		
		private void detach_FoodShopRelations(FoodShopRelation entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = null;
		}
		
		private void attach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = this;
		}
		
		private void detach_FoodShopRelationBuys(FoodShopRelationBuy entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.ShopLocation = null;
		}
	}
}
#pragma warning restore 1591
